name: MinefarmPlugin
version: '${project.version}'
main: org.oreoprojekt.minefarm.Minefarm
api-version: 1.17
authors: [ 0reo_0 ]
description: 마인팜
commands:
  cm:
    description: 채팅모드 전환
    aliases: [채팅]
  우편:
    aliases: [mail]
  우편함:
    aliases: [mailbox]
  우편정리:
    aliases: [mailclear, mailboxclear]
  섬:
    aliases: [tja]
  스폰:
    aliases: [spawn]
